<?php

namespace ACSEO\Bundle\BehatGeneratorBundle\Command;

use ACSEO\Bundle\BehatGeneratorBundle\Util\GherkinWriter as Writer;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\Filesystem\Filesystem;

/**
 * ACSEOAutomaticApiTestCommand creates automatic Behat features for api.
 */
class ACSEOAutomaticApiTestCommand extends ContainerAwareCommand
{
    protected $writer;

    /**
     * {@inheritdoc}
     */
    protected function configure()
    {
        $this
            ->setName('acseo:automatic-api-test')
            ->setDescription('Generate automatic tests for api')
        ;
    }

    /**
     * {@inheritdoc}
     *
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $this->io = new SymfonyStyle($input, $output);
        $this->writer = new Writer();

        $autoFeatureApiPath = $this->checkFolderStructure();

        $apiData = $this->getContainer()->get('nelmio_api_doc.extractor.api_doc_extractor')->all();
        $aggregates = $this->aggregate($apiData);

        foreach ($aggregates as $name => $aggregate) {
            if ($aggregate['CREATE'] !== null) {
                $test = $this->generateTest($name, $aggregate);
                file_put_contents($autoFeatureApiPath .'/'. $name .'.feature', $test);
                $this->io->success('Writing feature test for api resource: '. $name);
            } else {
                $this->io->warning('No route exists for creating '. $name .' in the api. No test created.');
            }
        }
    }

    /**
     * Aggregate api route by resource and actions.
     *
     * @param  array  $apiData
     * @return array
     */
    protected function aggregate(array $apiData = array())
    {
        if (count($apiData) === 0) {
            throw new \Exception('No data fetched from Nelmio api doc.');
        }

        $aggregate = array();
        foreach ($apiData as $data) {
            $data = $data['annotation'];
            $name = $data->getSection();
            if (!isset($aggregate[$name])) {
                $aggregate[$name] = array(
                    'CREATE' => null,
                    'GET_SINGLE' => null,
                    'GET_ALL' => null,
                    'EDIT' => null,
                    'DELETE' => null
                );
            }
            switch ($data->getMethod()) {
                case 'POST':
                    if ($this->isREST('CREATE', $data)) {
                        $aggregate[$name]['CREATE'] = $data;
                    }
                    break;
                case 'GET':
                    if (strpos($data->getResource(), '{id}') !== false) {
                        if ($this->isREST('GET_SINGLE', $data)) {
                            $aggregate[$name]['GET_SINGLE'] = $data;
                        }
                    } else {
                        if ($this->isREST('GET_ALL', $data)) {
                            $aggregate[$name]['GET_ALL'] = $data;
                        }
                    }
                    break;
                case 'PUT':
                    if ($this->isREST('EDIT', $data)) {
                        $aggregate[$data->getSection()]['EDIT'] = $data;
                    }
                    break;
                case 'DELETE':
                    if ($this->isREST('DELETE', $data)) {
                        $aggregate[$data->getSection()]['DELETE'] = $data;
                    }
                    break;
            }
        }

        return $aggregate;
    }

    /**
     * Generate test for an api resource.
     *
     * @param  string $name      is the name of the resource
     * @param  array  $aggregate is an aggregation of all rest routes of the api for the resource
     * @return string            is the test as string to save in a file
     */
    protected function generateTest($name, $aggregate)
    {
        $this->writer
            ->addLine('Feature: Automatic test for api resource '. $name)
            ->addLine('This test is automatically generated by ACSEOAutomaticApiTestCommand')
            ->addLine('Feel free to edit any part to adapt to specific situations')
            ->emptyLine()
                ->subLine('@createSchema')
        ;

        foreach ($aggregate as $action => $data) {
            if ($data !== null) {
                $this->writer
                    ->emptyLine()
                    ->addLine('Scenario: ' .  str_replace('_', ' ', $action) . ' ' . $name, 1)
                ;

                $url = $data->getResource();
                if (strpos($url, '{id}') !== false) {
                    $url = str_replace('{id}', '1', $url);
                }

                if (count($data->getParameters()) === 0) {
                    $this->writer->subLine('When I send a "'. $data->getMethod() .'" request to "'. $url .'"');

                } else {
                    $params = $this->generateFakeParams($data);
                    if (in_array($data->getMethod(), ['POST', 'PUT'])) {
                        $this->writer->subLine('When I send a "'. $data->getMethod() .'" request to "'. $url .'" with body:');
                    } else {
                        $this->writer->subLine('When I send a "'. $data->getMethod() .'" request to "'. $url .'" with parameters:');
                    }
                    $this->writer->addJson($params);
                }

                $this->writer
                    ->addLine('Then I should get a success code')
                    ->addLine('Then the url should match "'. $url .'"')
                ;
            }
        }

        return $this->writer->generateOutput();
    }

    /**
     * Check if needed folders are there, create them if not and return the path to the final directory.
     * @return string
     */
    protected function checkFolderStructure()
    {
        $fs = new Filesystem();
        $featurePath = $this->getContainer()->get('kernel')->getRootDir()."/../features";
        if(!$fs->exists($featurePath)) {
            throw new \Exception("The feature folder does not exist in this project");
        }
        $autoFeaturePath = $this->getContainer()->get('kernel')->getRootDir()."/../features/automatic";
        if(!$fs->exists($autoFeaturePath)) {
            $fs->mkdir($autoFeaturePath);
            $this->io->note("Creating the automatic folder in ".$featurePath);
        }
        $autoFeatureApiPath = $this->getContainer()->get('kernel')->getRootDir()."/../features/automatic/api";
        if(!$fs->exists($autoFeatureApiPath)) {
            $fs->mkdir($autoFeatureApiPath);
            $this->io->note("Creating the automatic folder in ".$autoFeaturePath);
        }

        return $autoFeatureApiPath;
    }

    /**
     * Generate fake parameters to send depending on parameters expected by the api.
     *
     * @param  array $data
     * @return array
     */
    protected function generateFakeParams($data)
    {
        $params = array();

        $faker = \Faker\Factory::create('fr_FR');

        foreach ($data->getParameters() as $name => $details) {

            // Make it fits to Faker

            // Integer
            if ('integer' === $details['dataType']) {
                $details['dataType'] = 'randomDigit';
            // Float
            } elseif ('float' === $details['dataType']) {
                $details['dataType'] = 'randomFloat';
            // String
            } elseif ('string' === $details['dataType']) {
                // Post code
                if (false !== stripos($name, 'zip')) {
                    $details['dataType'] = 'postcode';
                // Phone
                } elseif (false !== stripos($name, 'phone')) {
                    $details['dataType'] = 'phoneNumber';
                // Address
                } elseif (false !== stripos($name, 'location')) {
                    $details['dataType'] = 'address';
                // Url
                } elseif (false !== stripos($name, 'url')) {
                    $details['dataType'] = 'domainName';
                // Files (disabled for now - TODO)
                } elseif (false !== stripos($name, 'file') || false !== stripos($name, 'attachment')) {
                    $details['dataType'] = null;
                // Anything else
                } else {
                    $details['dataType'] = 'word';
                }
            // Datetime
            } elseif ('datetime' === $details['dataType']) {
                $details['dataType'] = 'iso8601';
            }

            // Try to get a value
            try {
                $params[$name] = $faker->$name;
            } catch (\Exception $e) {
                try {
                    $params[$name] = $faker->$details['dataType'];
                } catch (\Exception $e) {
                    $params[$name] = null;
                    if (true === $details['required']) {
                        $this->io->warning('Required parameter "'. $name .'" of type "'. $details['dataType'] .'" for resource "'. $data->getResource() .'" could not be generated by faking values. It has been set to null.');
                    }
                }
            }
        }

        return $params;
    }

    /**
     * Check if a route is REST.
     *
     * @param  string  $action
     * @param  [type]  $data
     * @return boolean
     */
    protected function isREST($action, $data)
    {
        $expected = '/'. $this->camelToSnakeCase($data->getSection()) .'s';

        switch ($action) {
            // Collection operations
            case 'CREATE':
            case 'GET_ALL':
                break;
            // Item operations
            case 'GET_SINGLE':
            case 'EDIT':
            case 'DELETE':
                $expected .= '/{id}';
                break;

            default:
                return false;
        }

        return $data->getResource() === $expected;
    }

    /**
     * Turn camelCase into snake_case.
     *
     * @param  string $input
     * @return string
     */
    protected function camelToSnakeCase($input)
    {
        preg_match_all('!([A-Z][A-Z0-9]*(?=$|[A-Z][a-z0-9])|[A-Za-z][a-z0-9]+)!', $input, $matches);
        $ret = $matches[0];
        foreach ($ret as &$match) {
            $match = $match == strtoupper($match) ? strtolower($match) : lcfirst($match);
        }

        return implode('_', $ret);
    }
}
